### ISSUE TITLE
Is awq_w_only.yml & awq_w4a16.yml use the same source code?

### ISSUE THREAD

**Issue by LiMa-cas** [ModelTC/llmc#116]
which awq_w_only.yml in /llmc/configs/quantization/methods/Awq/awq_w_only.yml and awq_w4a16.yml in /llmc/configs/quantization/backend/vllm，and I found the code awq.py in /llmc/llmc/compression/quantization/awq.py is different from autoawq which u have changed a lot. So I want to make sure if vllm also have the changes,thanks a lot!!!

**Comment by LiMa-cas** [comment]
other question，the failure using vllm to quantization：`2024-10-08 18:02:11.313 | INFO     | llmc.utils.utils:print_important_package_version:79 - torch : 2.4.0
2024-10-08 18:02:11.315 | INFO     | llmc.utils.utils:print_important_package_version:80 - transformers : 4.45.2
2024-10-08 18:02:11.315 | INFO     | llmc.utils.utils:print_important_package_version:81 - tokenizers : 0.20.0
2024-10-08 18:02:11.316 | INFO     | llmc.utils.utils:print_important_package_version:82 - huggingface-hub : 0.25.0
2024-10-08 18:02:11.316 | INFO     | llmc.utils.utils:print_important_package_version:83 - datasets : 3.0.0
2024-10-08 18:02:11.317 | INFO     | __main__:<module>:161 - WORLD_SIZE : 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/llmc/llmc/__main__.py", line 184, in <module>
[rank0]:     mkdirs(save_quant_path)
[rank0]:   File "/llmc/llmc/utils/utils.py", line 65, in mkdirs
[rank0]:     raise Exception(f'{path} existed before. Need check.')
[rank0]: Exception: /llmc/models/real_quant_model existed before. Need check.
[rank0]:[W1008 18:02:11.642536876 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1008 18:02:11.769000 140643769767744 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 1402604) of binary: /miniconda3/envs/llmc/bin/python
Traceback (most recent call last):
  File "/miniconda3/envs/llmc/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/llmc/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/miniconda3/envs/llmc/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/miniconda3/envs/llmc/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/miniconda3/envs/llmc/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/miniconda3/envs/llmc/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/llmc/llmc/__main__.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>`

**Comment by Harahan** [comment]
We only have one copy of the source code (`` /llmc/llmc/compression/quantization/*``). All ``*.yml``s are the configurations.

**Comment by LiMa-cas** [comment]
thanks a lot！！！
