### ISSUE TITLE
量化internlm2-chat-1_8b后，使用vllm推理时报错

### ISSUE THREAD

**Issue by baisesj** [ModelTC/llmc#221]
基于/configs/quantization/backend/vllm/下的rtn_w8a16.yml、awq_w4a16.yml，分别量化internlm2-chat-1_8b后，基于/examples/backend/vllm/infer_with_vllm.py脚本，使用vllm加载推理模型时均报错'model.layers.0.attention.wo.weight_packed'，麻烦请问是什么原因啊？
rtn_w8a16.yml设置如下：
base:
    seed: 42
model:
    type: InternLM2
    path: /data/home/songjj/base_llm_models/internlm2-chat-1_8b
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: /data/home/songjj/llmc/data/wikitext2/eval_wikitext2/
    bs: 1
    seq_len: 2048
    inference_per_block: False
    eval_token_consist: True
save:
    save_vllm: True
    save_path: /data/home/songjj/llmc/models_result_save/internlm2_for_vllm_rtn_w8a16/

infer_with_vllm.py设置如下：
model_path = '/data/home/songjj/llmc/models_result_save/internlm2_for_vllm_rtn_w8a16/vllm_quant_model'
model = LLM(model_path,trust_remote_code=True)

报错为：
INFO 11-22 14:11:26 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='/data/home/songjj/llmc/models_result_save/internlm2_for_vllm_rtn_w8a16/vllm_quant_model', speculative_config=None, tokenizer='/data/home/songjj/llmc/models_result_save/internlm2_for_vllm_rtn_w8a16/vllm_quant_model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=65536, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/data/home/songjj/llmc/models_result_save/internlm2_for_vllm_rtn_w8a16/vllm_quant_model)
INFO 11-22 14:11:28 selector.py:158] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 11-22 14:11:28 selector.py:51] Using XFormers backend.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.11.9 (you have 3.11.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
INFO 11-22 14:11:31 selector.py:158] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 11-22 14:11:31 selector.py:51] Using XFormers backend.
Traceback (most recent call last):
  File "/data/home/songjj/llmc/llmc-main/examples/backend/vllm/infer_with_vllm.py", line 5, in <module>
    model = LLM(model_path,trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 144, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 359, in from_engine_args
    engine = cls(
             ^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 222, in __init__
    self.model_executor = executor_class(
                          ^^^^^^^^^^^^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 41, in __init__
    self._init_executor()
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 24, in _init_executor
    self.driver_worker.load_model()
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/worker/worker.py", line 121, in load_model
    self.model_runner.load_model()
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 134, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 243, in load_model
    model.load_weights(
  File "/data/home/llm_dev/miniconda3/envs/sjj/lib/python3.11/site-packages/vllm/model_executor/models/internlm2.py", line 310, in load_weights
    param = params_dict[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'model.layers.0.attention.wo.weight_packed'

**Comment by gushiqiao** [comment]
已经修复，可以再试下最新的代码
