### ISSUE TITLE
Fail to test the generate api for smoothquant on qwen2-7b with lightllm

### ISSUE THREAD

**Issue by gloritygithub11** [ModelTC/llmc#41]
llmc build config
```
base:
    seed: &seed 42
model:
    type: Qwen2
    path: /models/Qwen2-7B-Instruct
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /models/src/llmc/tools/data/calib/pileval
    n_samples: 512
    bs: 1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    eval_pos: []
    name: wikitext2
    download: False
    path: /models/src/llmc/tools/data/eval/wikitext2
    bs: 1
    seq_len: 2048
quant:
    method: SmoothQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_trans: False
    save_lightllm: True
    save_path: ./save

```

it could build success. Then try to run and test with lightllm, lightllm could start success with following steps
```
cp /models/Qwen2-7B-Instruct/merges.txt /models/src/llmc/scripts/save/real_quant_model
cp /models/Qwen2-7B-Instruct/vocab.json /models/src/llmc/scripts/save/real_quant_model

python -m lightllm.server.api_server --model_dir /models/src/llmc/scripts/save/real_quant_model    \
                                     --host 0.0.0.0                 \
                                     --port 8080                    \
                                     --tp 1                         \
                                     --max_total_token_num 120000
```

start up console log
```
INFO 08-23 10:19:11 [api_server.py:471] use tgi api: False
INFO 08-23 10:19:11 [api_server.py:504] all start args:Namespace(host='0.0.0.0', port=8080, model_dir='/models/src/llmc/scripts/save/real_quant_model', tokenizer_mode='slow', load_way='HF', max_total_token_num=120000, batch_max_tokens=20000, eos_id=[2], running_max_req_size=1000, tp=1, max_req_input_len=2048, max_req_total_len=3072, nccl_port=28765, mode=[], trust_remote_code=False, disable_log_stats=False, log_stats_interval=10, router_token_ratio=0.0, router_max_new_token_len=1024, router_max_wait_tokens=10, use_dynamic_prompt_cache=False, splitfuse_block_size=256, splitfuse_mode=False, beam_mode=False, diverse_mode=False, token_healing_mode=False, enable_multimodal=False, cache_capacity=200, cache_reserved_ratio=0.5, data_type='float16', return_all_prompt_logprobs=False, use_reward_model=False, long_truncation_mode=None, use_tgi_api=False, health_monitor=False, metric_gateway=None, job_name='lightllm', grouping_key=[], push_interval=10, enable_monitor_auth=False)
INFO 08-23 10:19:15 [start_utils.py:29] init func start_metric_manager : init ok
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 08-23 10:19:15 [tokenizer.py:79] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
link shm 28765_mem_manger_can_use_token_num
link shm 28765_shared_token_load
INFO 08-23 10:19:20 [model_rpc.py:46] use ContinuesBatchBackend
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 08-23 10:19:20 [tokenizer.py:79] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 08-23 10:19:33 [mem_manager.py:29] mem manger get nccl port: 28765
link shm 28765_mem_manger_can_use_token_num
INFO 08-23 10:19:33 [base_backend.py:227] loaded model class <class 'lightllm.models.qwen2.model.Qwen2TpPartModel'>
INFO 08-23 10:19:33 [manager.py:110] use req queue ContinuesBatchQueue
INFO 08-23 10:19:33 [start_utils.py:29] init func start_router_process : init ok
INFO 08-23 10:19:33 [start_utils.py:29] init func start_detokenization_process : init ok
link shm 28765_shared_token_load
INFO:     Started server process [1717]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

test the generate api:
```
curl http://127.0.0.1:8080/generate     \
    -X POST                             \
    -d '{"inputs":"What is AI?","parameters":{"max_new_tokens":17, "frequency_penalty":1}}' \
    -H 'Content-Type: application/json'
```

get error:
```
INFO 08-23 10:20:52 [manager.py:105] recieved req X-Request-Id: X-Session-Id: start_time:2024-08-23 10:20:52 lightllm_req_id:0 
INFO 08-23 10:20:52 [manager.py:270] lightllm_req_id:0 prompt_cache_len:0 prompt_cache_ratio:0.0 
DEBUG 08-23 10:20:52 [manager.py:275] Init Batch: batch_id=06ead52e468a4bdaa5721ea52548e74b, time:1724408452.711206s req_ids:[0] 
DEBUG 08-23 10:20:52 [manager.py:275] 
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py:161> exception=RuntimeError('probability tensor contains either `inf`, `nan` or element < 0')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 166, in loop_for_fwd
    await self._step()
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 219, in _step
    await self._prefill_batch(self.running_batch)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 285, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 155, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 62, in exposed_prefill_batch
    return self.backend.prefill_batch(batch_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/utils/infer_utils.py", line 57, in inner_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/impl.py", line 18, in prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/impl.py", line 34, in forward
    next_token_ids, next_token_probs = sample(logits, run_reqs, self.eos_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/post_process.py", line 44, in sample
    sampled_index = torch.multinomial(probs_sort, num_samples=1, replacement=True)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by gloritygithub11** [comment]
I get similar error for model Llama-2-7b-hf
```
INFO 08-23 11:24:55 [manager.py:105] recieved req X-Request-Id: X-Session-Id: start_time:2024-08-23 11:24:55 lightllm_req_id:0 
INFO 08-23 11:24:55 [manager.py:270] lightllm_req_id:0 prompt_cache_len:0 prompt_cache_ratio:0.0 
DEBUG 08-23 11:24:55 [manager.py:275] Init Batch: batch_id=2d44628d924c482d9713d7a5ec7adad0, time:1724412295.7087991s req_ids:[0] 
DEBUG 08-23 11:24:55 [manager.py:275] 
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py:161> exception=RuntimeError('probability tensor contains either `inf`, `nan` or element < 0')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 166, in loop_for_fwd
    await self._step()
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 219, in _step
    await self._prefill_batch(self.running_batch)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/manager.py", line 285, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 155, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/model_rpc.py", line 62, in exposed_prefill_batch
    return self.backend.prefill_batch(batch_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/utils/infer_utils.py", line 57, in inner_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/impl.py", line 18, in prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/impl.py", line 34, in forward
    next_token_ids, next_token_probs = sample(logits, run_reqs, self.eos_id)
  File "/opt/conda/lib/python3.9/site-packages/lightllm-2.0.0-py3.9.egg/lightllm/server/router/model_infer/mode_backend/continues_batch/post_process.py", line 44, in sample
    sampled_index = torch.multinomial(probs_sort, num_samples=1, replacement=True)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by Harahan** [comment]
You can refer to the [doc](https://llmc-en.readthedocs.io/en/latest/) here. Code for directly load a real quantized model in lightllm has not been merged into the main branch. However,according to the doc, use ``save_trans`` in llmc, and then choose a weight-activation quantization mode in lightllm, which applies online naive quantization to the model. Finally, you can get a real quantized model with memory and time savings serving, and can talk with the model now.
