### ISSUE TITLE
fail to run awq on qwen2-7b-instruct

### ISSUE THREAD

**Issue by gloritygithub11** [ModelTC/llmc#55]
config:
```
base:
    seed: &seed 42
model:
    type: Qwen2
    path: /models/Qwen2-7B-Instruct
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /app/src/llmc/tools/data/calib/pileval
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: False
    path: /app/src/llmc/tools/data/eval/wikitext2
    bs: 1
    inference_per_block: False
    # For 70B model eval, bs can be set to 20, and inference_per_block can be set to True.
    # For 7B / 13B model eval, bs can be set to 1, and inference_per_block can be set to False.
    seq_len: 2048
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: learnable
    act:
        bit: 16
        symmetric: False
        granularity: per_token
        calib_algo: minmax
    special:
        trans: True
        trans_version: v2
        weight_clip: True
        clip_version: v2
        save_scale: True
        scale_path: ./save/qwen2-7b-instruct-awq_w4a16-best/scale
        save_clip: True
        clip_path: ./save/qwen2-7b-instruct-awq_w4a16-best/clip
save:
    save_trans: False
    save_quant: False
    save_path: ./save/qwen2-7b-instruct-awq_w4a16-best/default

```

result:
```
2024-08-28 11:02:15.575 | INFO     | llmc.compression.quantization.base_blockwise_quantization:deploy:813 - -- deploy_origin_float_model done --
Traceback (most recent call last):
  File "/app/src/llmc/llmc/__main__.py", line 170, in <module>
    main(config)
  File "/app/src/llmc/llmc/__main__.py", line 77, in main
    ppl = ppl_eval.eval(model)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/src/llmc/llmc/eval/eval_base.py", line 106, in eval
    eval_res = self.eval_func(model_fp, model)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/src/llmc/llmc/eval/eval_ppl.py", line 14, in eval_func
    self.testenc = self.testenc.input_ids
AttributeError: 'Tensor' object has no attribute 'input_ids'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1141) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/app/src/llmc/llmc/__main__.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-28_11:02:22
  host      : 025ef762cd3f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1141)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by gloritygithub11** [comment]
@LC-JiaZhaorong I'm running in ubuntu, looks like this file is for windows

**Comment by gloritygithub11** [comment]
looks like the issue has been fixed recently. After sync to the latest code, the problem does not exist.
